export const ACTIVITY_ACTIONS = {
  EVENT_CREATED: 'EVENT_CREATED',

  EVENT_UPDATED: 'EVENT_UPDATED',

  ADMIN_CREATED: 'ADMIN_CREATED',

  TICKET_SCANNED: 'TICKET_SCANNED',

  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
} as const;
